In [ ]:
import pandas as pd

In [ ]:
raw_data = pd.read_csv(r"test_path")

raw_data

,zapper_id,contact_number,last_tx_date,last_tx_ref,pending_earn_balance,pending_redeem_balance,cleared_balance,currency_id,points_earned
0,65f0a4dd-f642-4f97-a94e-0439c70ed1a9,639988453416,2024-01-05 07:55:52.654000+00:00,Z30905604729,0.0,0.0,230.00,981,0.0
1,bb0c2b3f-adee-46dc-b92b-29d4c97ea426,639171023436,2024-01-05 08:08:44.618000+00:00,Z32958373874,0.0,0.0,19.99,981,0.0
2,1a717714-41de-4a31-b2b3-8d26d7dcd612,639296458175,2024-01-05 08:19:57.174000+00:00,Z30156177104,0.0,0.0,740.00,981,0.0
3,4699fe97-5521-4a01-afdf-cede30148fa7,639673171002,2024-01-05 07:49:52.042000+00:00,Z34272433060,0.0,0.0,70.00,981,0.0
4,932a39d8-4ce3-4661-97a8-950be0c0baff,639328537161,2024-01-05 08:34:27.736000+00:00,Z32776342596,0.0,0.0,280.00,981,0.0
...,...,...,...,...,...,...,...,...,...
9788,7f2c743f-630d-4f13-a640-896e054a5c16,639918602289,2025-10-29 09:43:04.798000+00:00,Z31983189424,0.0,0.0,16.50,1050,0.0
9789,f8db358b-ee96-4dad-a751-3b253118210a,639298792397,2025-05-06 08:27:32.736000+00:00,Z30157860336,0.0,0.0,17.75,1050,0.0
9790,89d07d63-51f8-4152-9376-3c3dbec824c3,639761420542,2025-08-01 09:54:53.360000+00:00,Z31122878534,0.0,0.0,16.75,1050,0.0
9791,909f4b3b-4ad4-4dc3-af41-2aac60831890,639659364131,2025-07-06 04:44:25.694000+00:00,Z30294949356,0.0,0.0,15.25,1050,0.0
9792,aeb21dd6-22f9-4911-a60b-1c6a83904b01,639276116539,2025-11-22 04:40:00+00:00,Z30486800485,0.0,0.0,16.00,1050,0.0

In [3]:
clean_data = raw_data.loc[:, :]

clean_data["new_balance"] = clean_data["cleared_balance"] - clean_data["points_earned"]

clean_data = clean_data.loc[:, ["contact_number", "new_balance"]]

clean_data = clean_data[clean_data["new_balance"] > 0]

clean_data.to_csv(
    r"./test_files/2_columns_1.csv",
    index=False,
    header=False,
)

clean_data

      contact_number  new_balance
0       639988453416       230.00
1       639171023436        19.99
2       639296458175       740.00
3       639673171002        70.00
4       639328537161       280.00
...              ...          ...
9788    639918602289        16.50
9789    639298792397        17.75
9790    639761420542        16.75
9791    639659364131        15.25
9792    639276116539        16.00

[9563 rows x 2 columns]

In [4]:
chunksize = 1_000
for i, chunk in enumerate(pd.read_csv(r"./test_files/2_columns_1.csv", chunksize=chunksize)):
    print(
        f"Writing part {i + 1}, rows={len(chunk)}"
    )  # will show smaller size for last chunk
    chunk.to_csv(f"./test_files/big_part_1_{i + 1:03d}.csv", index=False, header=False)

Writing part 1, rows=1000
Writing part 2, rows=1000
Writing part 3, rows=1000
Writing part 4, rows=1000
Writing part 5, rows=1000
Writing part 6, rows=1000
Writing part 7, rows=1000
Writing part 8, rows=1000
Writing part 9, rows=1000
Writing part 10, rows=562