In [9]:
import polars as pl

In [ ]:
raw_data = pl.read_csv(
    r"test_path",
    schema_overrides={
        "pending_earn_balance": pl.Float64,
        "pending_redeem_balance": pl.Float64,
        "cleared_balance": pl.Float64,
        "currency_id": pl.Float64,
        "points_earned": pl.Float64,
    },
)

raw_data

shape: (9_793, 9)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ zapper_id ┆ contact_n ┆ last_tx_d ┆ last_tx_r ┆ … ┆ pending_r ┆ cleared_b ┆ currency_ ┆ points_e │
│ ---       ┆ umber     ┆ ate       ┆ ef        ┆   ┆ edeem_bal ┆ alance    ┆ id        ┆ arned    │
│ str       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ance      ┆ ---       ┆ ---       ┆ ---      │
│           ┆ i64       ┆ str       ┆ str       ┆   ┆ ---       ┆ f64       ┆ f64       ┆ f64      │
│           ┆           ┆           ┆           ┆   ┆ f64       ┆           ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 65f0a4dd- ┆ 639988453 ┆ 2024-01-0 ┆ Z30905604 ┆ … ┆ 0.0       ┆ 230.0     ┆ 981.0     ┆ 0.0      │
│ f642-4f97 ┆ 416       ┆ 5 07:55:5 ┆ 729       ┆   ┆           ┆           ┆           ┆          │
│ -a94e-043 ┆           ┆ 2.654000+ ┆           ┆   ┆           ┆           ┆           ┆          │
│ 9c7…      ┆           ┆ 00:…      ┆           ┆   ┆           ┆           ┆           ┆          │
│ bb0c2b3f- ┆ 639171023 ┆ 2024-01-0 ┆ Z32958373 ┆ … ┆ 0.0       ┆ 19.99     ┆ 981.0     ┆ 0.0      │
│ adee-46dc ┆ 436       ┆ 5 08:08:4 ┆ 874       ┆   ┆           ┆           ┆           ┆          │
│ -b92b-29d ┆           ┆ 4.618000+ ┆           ┆   ┆           ┆           ┆           ┆          │
│ 4c9…      ┆           ┆ 00:…      ┆           ┆   ┆           ┆           ┆           ┆          │
│ 1a717714- ┆ 639296458 ┆ 2024-01-0 ┆ Z30156177 ┆ … ┆ 0.0       ┆ 740.0     ┆ 981.0     ┆ 0.0      │
│ 41de-4a31 ┆ 175       ┆ 5 08:19:5 ┆ 104       ┆   ┆           ┆           ┆           ┆          │
│ -b2b3-8d2 ┆           ┆ 7.174000+ ┆           ┆   ┆           ┆           ┆           ┆          │
│ 6d7…      ┆           ┆ 00:…      ┆           ┆   ┆           ┆           ┆           ┆          │
│ 4699fe97- ┆ 639673171 ┆ 2024-01-0 ┆ Z34272433 ┆ … ┆ 0.0       ┆ 70.0      ┆ 981.0     ┆ 0.0      │
│ 5521-4a01 ┆ 002       ┆ 5 07:49:5 ┆ 060       ┆   ┆           ┆           ┆           ┆          │
│ -afdf-ced ┆           ┆ 2.042000+ ┆           ┆   ┆           ┆           ┆           ┆          │
│ e30…      ┆           ┆ 00:…      ┆           ┆   ┆           ┆           ┆           ┆          │
│ 932a39d8- ┆ 639328537 ┆ 2024-01-0 ┆ Z32776342 ┆ … ┆ 0.0       ┆ 280.0     ┆ 981.0     ┆ 0.0      │
│ 4ce3-4661 ┆ 161       ┆ 5 08:34:2 ┆ 596       ┆   ┆           ┆           ┆           ┆          │
│ -97a8-950 ┆           ┆ 7.736000+ ┆           ┆   ┆           ┆           ┆           ┆          │
│ be0…      ┆           ┆ 00:…      ┆           ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 7f2c743f- ┆ 639918602 ┆ 2025-10-2 ┆ Z31983189 ┆ … ┆ 0.0       ┆ 16.5      ┆ 1050.0    ┆ 0.0      │
│ 630d-4f13 ┆ 289       ┆ 9 09:43:0 ┆ 424       ┆   ┆           ┆           ┆           ┆          │
│ -a640-896 ┆           ┆ 4.798000+ ┆           ┆   ┆           ┆           ┆           ┆          │
│ e05…      ┆           ┆ 00:…      ┆           ┆   ┆           ┆           ┆           ┆          │
│ f8db358b- ┆ 639298792 ┆ 2025-05-0 ┆ Z30157860 ┆ … ┆ 0.0       ┆ 17.75     ┆ 1050.0    ┆ 0.0      │
│ ee96-4dad ┆ 397       ┆ 6 08:27:3 ┆ 336       ┆   ┆           ┆           ┆           ┆          │
│ -a751-3b2 ┆           ┆ 2.736000+ ┆           ┆   ┆           ┆           ┆           ┆          │
│ 531…      ┆           ┆ 00:…      ┆           ┆   ┆           ┆           ┆           ┆          │
│ 89d07d63- ┆ 639761420 ┆ 2025-08-0 ┆ Z31122878 ┆ … ┆ 0.0       ┆ 16.75     ┆ 1050.0    ┆ 0.0      │
│ 51f8-4152 ┆ 542       ┆ 1 09:54:5 ┆ 534       ┆   ┆           ┆           ┆           ┆          │
│ -9376-3c3 ┆           ┆ 3.360000+ ┆           ┆   ┆           ┆           ┆           ┆          │
│ dbe…      ┆           ┆ 00:…      ┆           ┆   ┆           ┆           ┆           ┆          │
│ 909f4b3b- ┆ 639659364 ┆ 2025-07-0 ┆ Z30294949 ┆ … ┆ 0.0       ┆ 15.25     ┆ 1050.0    ┆ 0.0      │
│ 4ad4-4dc3 ┆ 131       ┆ 6 04:44:2 ┆ 356       ┆   ┆           ┆           ┆           ┆          │
│ -af41-2aa ┆           ┆ 5.694000+ ┆           ┆   ┆           ┆           ┆           ┆          │
│ c60…      ┆           ┆ 00:…      ┆           ┆   ┆           ┆           ┆           ┆          │
│ aeb21dd6- ┆ 639276116 ┆ 2025-11-2 ┆ Z30486800 ┆ … ┆ 0.0       ┆ 16.0      ┆ 1050.0    ┆ 0.0      │
│ 22f9-4911 ┆ 539       ┆ 2 04:40:0 ┆ 485       ┆   ┆           ┆           ┆           ┆          │
│ -a60b-1c6 ┆           ┆ 0+00:00   ┆           ┆   ┆           ┆           ┆           ┆          │
│ a83…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [11]:
clean_data = (
    raw_data.with_columns(
        (pl.col("cleared_balance") - pl.col("points_earned")).alias("new_balance")
    )
    .select(["contact_number", "new_balance"])
    .filter(pl.col("new_balance") > 0)
)

clean_data.write_csv("./test_files/2_columns_2.csv", include_header=False)
clean_data

shape: (9_563, 2)
┌────────────────┬─────────────┐
│ contact_number ┆ new_balance │
│ ---            ┆ ---         │
│ i64            ┆ f64         │
╞════════════════╪═════════════╡
│ 639988453416   ┆ 230.0       │
│ 639171023436   ┆ 19.99       │
│ 639296458175   ┆ 740.0       │
│ 639673171002   ┆ 70.0        │
│ 639328537161   ┆ 280.0       │
│ …              ┆ …           │
│ 639918602289   ┆ 16.5        │
│ 639298792397   ┆ 17.75       │
│ 639761420542   ┆ 16.75       │
│ 639659364131   ┆ 15.25       │
│ 639276116539   ┆ 16.0        │
└────────────────┴─────────────┘

In [12]:
chunksize = 1_000
reader = pl.read_csv_batched(r"./test_files/2_columns_2.csv", batch_size=chunksize)

part = 0
while True:
    batches = reader.next_batches(1)  # get up to 1 DataFrame of batch_size
    if not batches:
        break
    for df in batches:
        part += 1
        print(f"Writing part {part}, rows={df.shape[0]}")
        df.write_csv(f"./test_files/big_part_2_{part:03d}.csv", include_header=False)

Writing part 1, rows=1000
Writing part 2, rows=1000
Writing part 3, rows=1000
Writing part 4, rows=1000
Writing part 5, rows=1000
Writing part 6, rows=1000
Writing part 7, rows=1000
Writing part 8, rows=1000
Writing part 9, rows=1000
Writing part 10, rows=562

/var/folders/bj/0krk4gq13b9132z5f9h60ycm0000gn/T/ipykernel_8222/2719638118.py:2: DeprecationWarning: `read_csv_batched` is deprecated; use `scan_csv().collect_batches()` instead.
  reader = pl.read_csv_batched(r"./test_files/2_columns_2.csv", batch_size=chunksize)